Player can generate obstacles.
SiT-Academy-Students/Labyrinth pull request #15
Opened 2023-04-27 09:26 UTC by ChristopherPetrov

Instead of using random positions, the player now can generate obstacles right to himself. The edges are randomized.

![Screenshot 2023-04-27 121154](https://user-images.githubusercontent.com/120673989/234820275-094c19b0-0558-4ec8-96d0-033cddba5a40.png)

2023-05-04 16:48 UTC, TonyTroeff reviewed
Try with rebuild.
If this did not help, run `dotnet restore` or `dotnet restore --force` at the root folder.

2023-05-25 15:45 UTC, TonyTroeff requested changes

2023-05-25 15:45 UTC, TonyTroeff commented on Labyrinth.Console/Constants.cs
> +        public const int systemRows = 1;
Use PascalCase

2023-05-25 15:45 UTC, TonyTroeff commented on Labyrinth.Console/MapGenerator.cs
> +        private static int leftBorder => 33;
Too much magic over here.

2023-05-25 15:45 UTC, TonyTroeff commented on Labyrinth.Console/MapGenerator.cs
> +        private static int rightBorder => System.Console.LargestWindowWidth - 20;
We should not depend on the Console.

2023-05-25 15:45 UTC, TonyTroeff commented on Labyrinth.Console/MapGenerator.cs
> +        Dictionary<Coordinates, Obstacle> _obstaclesDict { get; }
Either make this a field, or use the appropriate naming convention (PascalCase)

2023-05-25 15:45 UTC, TonyTroeff commented on Labyrinth.Console/MapGenerator.cs
> +        public void RenderObstacle(Obstacle obstacle)
It is good that we have extracted such a method. However, this is not the correct place for it. I would consider moving it to a static class.

2023-05-25 15:45 UTC, TonyTroeff commented on Labyrinth.Console/MapGenerator.cs
> +                    if (x + 1 == rightBorder) whatEdges += 4;
The magic continues.

2023-05-25 15:45 UTC, TonyTroeff commented on Labyrinth.Console/MapGenerator.cs
> +//Top = 1, ═
No need for these comments.

2023-05-25 15:45 UTC, TonyTroeff commented on Labyrinth.Console/MapGenerator.cs
> +                    if (x + 1 == rightBorder) whatEdges += 4;
Use bitwise OR wherever this is possible.

2023-05-25 15:45 UTC, TonyTroeff commented on Labyrinth.Console/MapGenerator.cs
> +                    if (x + 1 == rightBorder) whatEdges += 4;
Potentially, improve the complexity of this algorithm.

2023-06-01 18:39 UTC, TonyTroeff requested changes

2023-06-01 18:39 UTC, TonyTroeff commented on Labyrinth.Console/Controllers/IFlowController.cs
> +        public void QuickObstacleGeneration(Coordinates currentCoordinates, ObstacleEdges currentEdges);
I think this method is not necessary.

2023-06-01 18:39 UTC, TonyTroeff commented on Labyrinth.Console/MapGenerator.cs
> +        public MapGenerator(Dictionary<Coordinates, Obstacle> obstaclesDict, IFlowController flowController, int rightBorder, int leftBorder, int topBorder, int botBorder)
Merge `main` and simplify this using the incoming changes.

2023-06-01 18:39 UTC, TonyTroeff commented on Labyrinth.Console/MapGenerator.cs
> +        public void QuickObstacleGeneration(Coordinates currentCoordinates, ObstacleEdges currentEdges)
I see this method for the second time now. Still, do not think it is necessary.

2023-06-01 18:39 UTC, TonyTroeff commented on Labyrinth.Console/MapGenerator.cs
> +        public void GenerateXAxisBorders(int cycleStart, int cycleEnd, Coordinates topBorderLocation, Coordinates bottomBorderLocation, ObstacleEdges edgeOrientation)
Try to simplify this using the private fields.

2023-06-07 06:36 UTC, ChristopherPetrov commented on Labyrinth.Console/MapGenerator.cs
> +//Top = 1, ═
Removed the commends.

2023-06-15 18:23 UTC, TonyTroeff approved these changes

2023-06-15 18:24 UTC, merged